# Generated by Django 3.2 on 2021-10-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='nothing', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default='nothing', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='city',
            field=models.CharField(default='nothing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='state',
            field=models.CharField(default='nothing', max_length=20, null=True),
        ),
    ]
