# Generated by Django 3.2 on 2021-10-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211013_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='remarks',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
