# Generated by Django 3.2 on 2021-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211013_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='banner',
            field=models.ImageField(default='banner.png', upload_to='banners'),
        ),
    ]
