# Generated by Django 3.2 on 2021-10-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211020_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='area',
            field=models.CharField(default='nothing', max_length=60),
        ),
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(default='nothing', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='no_of_bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='no_of_bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='property_name',
            field=models.CharField(default='nothing', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='property_type',
            field=models.CharField(default='nothing', max_length=60),
        ),
        migrations.AddField(
            model_name='review',
            name='state',
            field=models.CharField(default='nothing', max_length=20),
        ),
    ]
